test: add homepage and cookies banner e2e tests
netguru/inicjatywyotwarte-fe pull request #28
Opened 2020-08-31 15:07 UTC by bartosobczynski

2020-09-03 12:09 UTC, jjkazm commented on cypress/integration/AddInitiative.spec.js
> +    cy.get('input[id="app-name"]').type('Nazwa inicjatywy')
Maybe change it to `data-cy`? Ideally with some helper for more human-readable tests :)

2020-09-03 12:19 UTC, jjkazm commented on cypress/integration/Search.spec.js
> +    cy.get('[data-cy="resource-tile"]').should('have.length', 1)
I'v seen this assertion before in the code, but I wonder if we really want to check if it's only one element with this data mark. Please note, the `get` in cypress is a default assertion. more on it [here](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Default-Assertions)

2020-09-03 12:35 UTC, jjkazm commented on src/hooks/useFetchedInitiatives.js
> +};
maybe?

```suggestion
const filterInitiatives = (initiatives, category) => 
  category ? filter(initiatives, ['attributes.category', category]) : initiatives
```

2020-09-03 12:48 UTC, jjkazm commented on src/hooks/useFetchedTags.js
> +    }
how about taking this part outside of useEffect? something like `if(isDevelopmentEnv) { return mockedTags }` Seems it should work since it should be run only once.

2020-09-03 12:51 UTC, jjkazm commented on src/pages/OneResourcePage/OneResourcePage.js
> +  }
do you think the below would work as expected ?
```suggestion 
const initiative = () =>
  resourceId ? find(initiatives, ['id', resourceId]) : null
```

2020-09-03 12:55 UTC, jjkazm commented on src/hooks/useFetchedLocations.js
> +import { mockedLocations } from 'constants/mockedData'
seems like this hook and the below one could be merged and reused. Even the above would be possible. Eg with argument `dependsOn: category`

2020-09-03 12:56 UTC, jjkazm requested changes
Nice work 🚀  I left few comments, but these are mostly suggestions/questions rather than change requests :)

2020-09-07 07:13 UTC, bartosobczynski commented on cypress/integration/AddInitiative.spec.js
> +    cy.get('input[id="app-name"]').type('Nazwa inicjatywy')
Done :)

2020-09-07 07:14 UTC, bartosobczynski commented on cypress/integration/Search.spec.js
> +    cy.get('[data-cy="resource-tile"]').should('have.length', 1)
Yes, here in this particular search i'd like to test exact count of data, as I am testing search feature, I want to be sure there is one result, not two :)

2020-09-07 07:28 UTC, jjkazm commented on src/hooks/useFetchedTags.js
> +
```suggestion
if (isDevelopmentEnv) { return mockedTags };
```

2020-09-07 09:16 UTC, merged